# GFN tuning
TACTIC_DELIMITER = "\n" 
PROOF_COMPLETE_MESSAGE = "No goals"
LEAN_DOJO_RANDOM_DATA_PATH = "data/leandojo_benchmark_4/random/"
DEFAULT_VERIFIER_BATCH_SIZE = 1
DEFAULT_VERIFIER_ADAPTER_NAME = "verifier"
DEFAULT_GENERATOR_ADAPTER_NAME = "generator"
