# repo
repo: "/root/gfn_ntp/"

# path to .env file defining env variable: GITHUB_ACCESS_TOKEN 
github_access_token: "/root/gfn_ntp/.env"

# '' same but for HF_ACCESS_TOKEN
hf_access_token: "/root/gfn_ntp/.env"

# directory to store lean dojo cache 
# (if none, defaults to $HOME/.cache/lean_dojo)
lean_dojo_cache_path: "/root/gfn_ntp/.cache/lean_dojo"
